#!/usr/bin/env python

from os import system

def dump(obj):
	i = obj.iterkeys
	return "\n".join(map(lambda(x): x + ':' + str(obj[x]),i()))

system("./dbtool/dbtool 0 add cs '" + dump({
	'name' : 'dave.dloh.org',
	'ipaddr' : '0.0.0.0',
	'port' : 9996,
	'nat_port' : '9996',
	'admins' : ''
}) + "'")
